// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: EIHCameraAPI.proto

#include "EIHCameraAPI.pb.h"
#include "EIHCameraAPI.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace TmEIHCamera {

static const char* EIHCameraApi_method_names[] = {
  "/TmEIHCamera.EIHCameraApi/isCameraConnected",
  "/TmEIHCamera.EIHCameraApi/getIntrinsics",
  "/TmEIHCamera.EIHCameraApi/getHandEyeParameters",
  "/TmEIHCamera.EIHCameraApi/getImageData",
  "/TmEIHCamera.EIHCameraApi/getImageConfiguration",
  "/TmEIHCamera.EIHCameraApi/terminateCameraConnection",
  "/TmEIHCamera.EIHCameraApi/resumeCameraConnection",
  "/TmEIHCamera.EIHCameraApi/getCapturingSettings",
  "/TmEIHCamera.EIHCameraApi/setCapturingSettings",
  "/TmEIHCamera.EIHCameraApi/getShutterTime",
  "/TmEIHCamera.EIHCameraApi/setShutterTime",
  "/TmEIHCamera.EIHCameraApi/getGain",
  "/TmEIHCamera.EIHCameraApi/setGain",
  "/TmEIHCamera.EIHCameraApi/getWhiteBalance",
  "/TmEIHCamera.EIHCameraApi/setWhiteBalance",
  "/TmEIHCamera.EIHCameraApi/getFocus",
  "/TmEIHCamera.EIHCameraApi/setFocus",
  "/TmEIHCamera.EIHCameraApi/getImageSize",
  "/TmEIHCamera.EIHCameraApi/setImageSize",
};

std::unique_ptr< EIHCameraApi::Stub> EIHCameraApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EIHCameraApi::Stub> stub(new EIHCameraApi::Stub(channel, options));
  return stub;
}

EIHCameraApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_isCameraConnected_(EIHCameraApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getIntrinsics_(EIHCameraApi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getHandEyeParameters_(EIHCameraApi_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getImageData_(EIHCameraApi_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getImageConfiguration_(EIHCameraApi_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_terminateCameraConnection_(EIHCameraApi_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_resumeCameraConnection_(EIHCameraApi_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getCapturingSettings_(EIHCameraApi_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setCapturingSettings_(EIHCameraApi_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getShutterTime_(EIHCameraApi_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setShutterTime_(EIHCameraApi_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getGain_(EIHCameraApi_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setGain_(EIHCameraApi_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getWhiteBalance_(EIHCameraApi_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setWhiteBalance_(EIHCameraApi_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getFocus_(EIHCameraApi_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setFocus_(EIHCameraApi_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getImageSize_(EIHCameraApi_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setImageSize_(EIHCameraApi_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status EIHCameraApi::Stub::isCameraConnected(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::isCameraConnectedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::isCameraConnectedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_isCameraConnected_, context, request, response);
}

void EIHCameraApi::Stub::async::isCameraConnected(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::isCameraConnectedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::isCameraConnectedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_isCameraConnected_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::isCameraConnected(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::isCameraConnectedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_isCameraConnected_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::isCameraConnectedResponse>* EIHCameraApi::Stub::PrepareAsyncisCameraConnectedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::isCameraConnectedResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_isCameraConnected_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::isCameraConnectedResponse>* EIHCameraApi::Stub::AsyncisCameraConnectedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncisCameraConnectedRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getIntrinsics(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::getIntrinsicsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getIntrinsicsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getIntrinsics_, context, request, response);
}

void EIHCameraApi::Stub::async::getIntrinsics(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getIntrinsicsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getIntrinsicsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getIntrinsics_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getIntrinsics(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getIntrinsicsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getIntrinsics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getIntrinsicsResponse>* EIHCameraApi::Stub::PrepareAsyncgetIntrinsicsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::getIntrinsicsResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getIntrinsics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getIntrinsicsResponse>* EIHCameraApi::Stub::AsyncgetIntrinsicsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetIntrinsicsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getHandEyeParameters(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::Camera_HandEyeParameters* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_HandEyeParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getHandEyeParameters_, context, request, response);
}

void EIHCameraApi::Stub::async::getHandEyeParameters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_HandEyeParameters* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_HandEyeParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getHandEyeParameters_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getHandEyeParameters(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_HandEyeParameters* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getHandEyeParameters_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_HandEyeParameters>* EIHCameraApi::Stub::PrepareAsyncgetHandEyeParametersRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::Camera_HandEyeParameters, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getHandEyeParameters_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_HandEyeParameters>* EIHCameraApi::Stub::AsyncgetHandEyeParametersRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetHandEyeParametersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getImageData(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::Camera_Image_Data* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_Image_Data, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getImageData_, context, request, response);
}

void EIHCameraApi::Stub::async::getImageData(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_Image_Data* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_Image_Data, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getImageData_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getImageData(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_Image_Data* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getImageData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_Image_Data>* EIHCameraApi::Stub::PrepareAsyncgetImageDataRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::Camera_Image_Data, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getImageData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_Image_Data>* EIHCameraApi::Stub::AsyncgetImageDataRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetImageDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getImageConfiguration(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::Camera_Image_Configuration* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_Image_Configuration, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getImageConfiguration_, context, request, response);
}

void EIHCameraApi::Stub::async::getImageConfiguration(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_Image_Configuration* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_Image_Configuration, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getImageConfiguration_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getImageConfiguration(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_Image_Configuration* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getImageConfiguration_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_Image_Configuration>* EIHCameraApi::Stub::PrepareAsyncgetImageConfigurationRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::Camera_Image_Configuration, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getImageConfiguration_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_Image_Configuration>* EIHCameraApi::Stub::AsyncgetImageConfigurationRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetImageConfigurationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::terminateCameraConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_terminateCameraConnection_, context, request, response);
}

void EIHCameraApi::Stub::async::terminateCameraConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_terminateCameraConnection_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::terminateCameraConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_terminateCameraConnection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncterminateCameraConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_terminateCameraConnection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncterminateCameraConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncterminateCameraConnectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::resumeCameraConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_resumeCameraConnection_, context, request, response);
}

void EIHCameraApi::Stub::async::resumeCameraConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_resumeCameraConnection_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::resumeCameraConnection(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_resumeCameraConnection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncresumeCameraConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_resumeCameraConnection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncresumeCameraConnectionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncresumeCameraConnectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getCapturingSettings(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::Camera_CapturingSettings* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_CapturingSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getCapturingSettings_, context, request, response);
}

void EIHCameraApi::Stub::async::getCapturingSettings(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_CapturingSettings* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::Camera_CapturingSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getCapturingSettings_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getCapturingSettings(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_CapturingSettings* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getCapturingSettings_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_CapturingSettings>* EIHCameraApi::Stub::PrepareAsyncgetCapturingSettingsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::Camera_CapturingSettings, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getCapturingSettings_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::Camera_CapturingSettings>* EIHCameraApi::Stub::AsyncgetCapturingSettingsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetCapturingSettingsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::setCapturingSettings(::grpc::ClientContext* context, const ::TmEIHCamera::setCapturingSettingsRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TmEIHCamera::setCapturingSettingsRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setCapturingSettings_, context, request, response);
}

void EIHCameraApi::Stub::async::setCapturingSettings(::grpc::ClientContext* context, const ::TmEIHCamera::setCapturingSettingsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TmEIHCamera::setCapturingSettingsRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setCapturingSettings_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::setCapturingSettings(::grpc::ClientContext* context, const ::TmEIHCamera::setCapturingSettingsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setCapturingSettings_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncsetCapturingSettingsRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setCapturingSettingsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::TmEIHCamera::setCapturingSettingsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setCapturingSettings_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncsetCapturingSettingsRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setCapturingSettingsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetCapturingSettingsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getShutterTime(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::getShutterTimeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getShutterTimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getShutterTime_, context, request, response);
}

void EIHCameraApi::Stub::async::getShutterTime(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getShutterTimeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getShutterTimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getShutterTime_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getShutterTime(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getShutterTimeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getShutterTime_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getShutterTimeResponse>* EIHCameraApi::Stub::PrepareAsyncgetShutterTimeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::getShutterTimeResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getShutterTime_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getShutterTimeResponse>* EIHCameraApi::Stub::AsyncgetShutterTimeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetShutterTimeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::setShutterTime(::grpc::ClientContext* context, const ::TmEIHCamera::setShutterTimeRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TmEIHCamera::setShutterTimeRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setShutterTime_, context, request, response);
}

void EIHCameraApi::Stub::async::setShutterTime(::grpc::ClientContext* context, const ::TmEIHCamera::setShutterTimeRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TmEIHCamera::setShutterTimeRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setShutterTime_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::setShutterTime(::grpc::ClientContext* context, const ::TmEIHCamera::setShutterTimeRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setShutterTime_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncsetShutterTimeRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setShutterTimeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::TmEIHCamera::setShutterTimeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setShutterTime_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncsetShutterTimeRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setShutterTimeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetShutterTimeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getGain(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::getGainResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getGainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getGain_, context, request, response);
}

void EIHCameraApi::Stub::async::getGain(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getGainResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getGainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getGain_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getGain(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getGainResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getGain_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getGainResponse>* EIHCameraApi::Stub::PrepareAsyncgetGainRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::getGainResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getGain_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getGainResponse>* EIHCameraApi::Stub::AsyncgetGainRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetGainRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::setGain(::grpc::ClientContext* context, const ::TmEIHCamera::setGainRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TmEIHCamera::setGainRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setGain_, context, request, response);
}

void EIHCameraApi::Stub::async::setGain(::grpc::ClientContext* context, const ::TmEIHCamera::setGainRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TmEIHCamera::setGainRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setGain_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::setGain(::grpc::ClientContext* context, const ::TmEIHCamera::setGainRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setGain_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncsetGainRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setGainRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::TmEIHCamera::setGainRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setGain_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncsetGainRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setGainRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetGainRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getWhiteBalance(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::getWhiteBalanceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getWhiteBalanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getWhiteBalance_, context, request, response);
}

void EIHCameraApi::Stub::async::getWhiteBalance(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getWhiteBalanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getWhiteBalanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getWhiteBalance_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getWhiteBalance(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getWhiteBalanceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getWhiteBalance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getWhiteBalanceResponse>* EIHCameraApi::Stub::PrepareAsyncgetWhiteBalanceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::getWhiteBalanceResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getWhiteBalance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getWhiteBalanceResponse>* EIHCameraApi::Stub::AsyncgetWhiteBalanceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetWhiteBalanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::setWhiteBalance(::grpc::ClientContext* context, const ::TmEIHCamera::setWhiteBalanceRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TmEIHCamera::setWhiteBalanceRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setWhiteBalance_, context, request, response);
}

void EIHCameraApi::Stub::async::setWhiteBalance(::grpc::ClientContext* context, const ::TmEIHCamera::setWhiteBalanceRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TmEIHCamera::setWhiteBalanceRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setWhiteBalance_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::setWhiteBalance(::grpc::ClientContext* context, const ::TmEIHCamera::setWhiteBalanceRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setWhiteBalance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncsetWhiteBalanceRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setWhiteBalanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::TmEIHCamera::setWhiteBalanceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setWhiteBalance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncsetWhiteBalanceRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setWhiteBalanceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetWhiteBalanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getFocus(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::getFocusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getFocusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getFocus_, context, request, response);
}

void EIHCameraApi::Stub::async::getFocus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getFocusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getFocusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getFocus_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getFocus(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getFocusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getFocus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getFocusResponse>* EIHCameraApi::Stub::PrepareAsyncgetFocusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::getFocusResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getFocus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getFocusResponse>* EIHCameraApi::Stub::AsyncgetFocusRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetFocusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::setFocus(::grpc::ClientContext* context, const ::TmEIHCamera::setFocusRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TmEIHCamera::setFocusRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setFocus_, context, request, response);
}

void EIHCameraApi::Stub::async::setFocus(::grpc::ClientContext* context, const ::TmEIHCamera::setFocusRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TmEIHCamera::setFocusRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setFocus_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::setFocus(::grpc::ClientContext* context, const ::TmEIHCamera::setFocusRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setFocus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncsetFocusRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setFocusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::TmEIHCamera::setFocusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setFocus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncsetFocusRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setFocusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetFocusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::getImageSize(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::TmEIHCamera::getImageSizeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getImageSizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getImageSize_, context, request, response);
}

void EIHCameraApi::Stub::async::getImageSize(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getImageSizeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::TmEIHCamera::getImageSizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getImageSize_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::getImageSize(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getImageSizeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getImageSize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getImageSizeResponse>* EIHCameraApi::Stub::PrepareAsyncgetImageSizeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TmEIHCamera::getImageSizeResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getImageSize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TmEIHCamera::getImageSizeResponse>* EIHCameraApi::Stub::AsyncgetImageSizeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetImageSizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EIHCameraApi::Stub::setImageSize(::grpc::ClientContext* context, const ::TmEIHCamera::setImageSizeRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TmEIHCamera::setImageSizeRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setImageSize_, context, request, response);
}

void EIHCameraApi::Stub::async::setImageSize(::grpc::ClientContext* context, const ::TmEIHCamera::setImageSizeRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TmEIHCamera::setImageSizeRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setImageSize_, context, request, response, std::move(f));
}

void EIHCameraApi::Stub::async::setImageSize(::grpc::ClientContext* context, const ::TmEIHCamera::setImageSizeRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setImageSize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::PrepareAsyncsetImageSizeRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setImageSizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::TmEIHCamera::setImageSizeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setImageSize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* EIHCameraApi::Stub::AsyncsetImageSizeRaw(::grpc::ClientContext* context, const ::TmEIHCamera::setImageSizeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetImageSizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

EIHCameraApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::isCameraConnectedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::isCameraConnectedResponse* resp) {
               return service->isCameraConnected(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::getIntrinsicsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::getIntrinsicsResponse* resp) {
               return service->getIntrinsics(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::Camera_HandEyeParameters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::Camera_HandEyeParameters* resp) {
               return service->getHandEyeParameters(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::Camera_Image_Data, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::Camera_Image_Data* resp) {
               return service->getImageData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::Camera_Image_Configuration, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::Camera_Image_Configuration* resp) {
               return service->getImageConfiguration(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::Empty* resp) {
               return service->terminateCameraConnection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::Empty* resp) {
               return service->resumeCameraConnection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::Camera_CapturingSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::Camera_CapturingSettings* resp) {
               return service->getCapturingSettings(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::TmEIHCamera::setCapturingSettingsRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TmEIHCamera::setCapturingSettingsRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->setCapturingSettings(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::getShutterTimeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::getShutterTimeResponse* resp) {
               return service->getShutterTime(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::TmEIHCamera::setShutterTimeRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TmEIHCamera::setShutterTimeRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->setShutterTime(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::getGainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::getGainResponse* resp) {
               return service->getGain(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::TmEIHCamera::setGainRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TmEIHCamera::setGainRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->setGain(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::getWhiteBalanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::getWhiteBalanceResponse* resp) {
               return service->getWhiteBalance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::TmEIHCamera::setWhiteBalanceRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TmEIHCamera::setWhiteBalanceRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->setWhiteBalance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::getFocusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::getFocusResponse* resp) {
               return service->getFocus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::TmEIHCamera::setFocusRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TmEIHCamera::setFocusRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->setFocus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::google::protobuf::Empty, ::TmEIHCamera::getImageSizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::TmEIHCamera::getImageSizeResponse* resp) {
               return service->getImageSize(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EIHCameraApi_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EIHCameraApi::Service, ::TmEIHCamera::setImageSizeRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EIHCameraApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TmEIHCamera::setImageSizeRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->setImageSize(ctx, req, resp);
             }, this)));
}

EIHCameraApi::Service::~Service() {
}

::grpc::Status EIHCameraApi::Service::isCameraConnected(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::isCameraConnectedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getIntrinsics(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getIntrinsicsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getHandEyeParameters(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_HandEyeParameters* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getImageData(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_Image_Data* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getImageConfiguration(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_Image_Configuration* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::terminateCameraConnection(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::resumeCameraConnection(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getCapturingSettings(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::Camera_CapturingSettings* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::setCapturingSettings(::grpc::ServerContext* context, const ::TmEIHCamera::setCapturingSettingsRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getShutterTime(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getShutterTimeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::setShutterTime(::grpc::ServerContext* context, const ::TmEIHCamera::setShutterTimeRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getGain(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getGainResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::setGain(::grpc::ServerContext* context, const ::TmEIHCamera::setGainRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getWhiteBalance(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getWhiteBalanceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::setWhiteBalance(::grpc::ServerContext* context, const ::TmEIHCamera::setWhiteBalanceRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getFocus(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getFocusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::setFocus(::grpc::ServerContext* context, const ::TmEIHCamera::setFocusRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::getImageSize(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::TmEIHCamera::getImageSizeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EIHCameraApi::Service::setImageSize(::grpc::ServerContext* context, const ::TmEIHCamera::setImageSizeRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TmEIHCamera

